import {videoThumbnail} from '../Assets';
export const video_data = [
  {
    id: 1,
    author: 'Andy William',
    video_title: 'Basic: how to ride your skateboard comfortly',
    duration: '7 min',
    views: '32K',
    thumbnail: videoThumbnail,
    type: 'free',
  },
  {
    id: 2,
    author: 'Andy William',
    video_title: 'Basic: how to ride your skateboard comfortly',
    duration: '7 min',
    views: '32K',
    thumbnail: videoThumbnail,
    type: 'free',
  },
  {
    id: 3,
    author: 'Andy William',
    video_title: 'Basic: how to ride your skateboard comfortly',
    duration: '7 min',
    views: '32K',
    thumbnail: videoThumbnail,
    type: 'free',
  },
  {
    id: 4,
    author: 'Andy William',
    video_title: 'Basic: how to ride your skateboard comfortly',
    duration: '7 min',
    views: '32K',
    thumbnail: videoThumbnail,
    type: 'free',
  },
  {
    id: 5,
    author: 'Andy William',
    video_title: 'Basic: how to ride your skateboard comfortly',
    duration: '7 min',
    views: '32K',
    thumbnail: videoThumbnail,
    type: 'free',
  },
  {
    id: 6,
    author: 'Andy William',
    video_title: 'Basic: how to ride your skateboard comfortly',
    duration: '7 min',
    views: '32K',
    thumbnail: videoThumbnail,
    type: 'free',
  },
];

export const videos = [
  {
    id: 1,
    author: 'Andy William',
    video_title: 'Basic: how to ride your skateboard comfortly',
    duration: '7 min',
    views: '32K',
    thumbnail: videoThumbnail,
    type: 'free',
    videoLink: 'https://www.taxmann.com/emailer/images/CompaniesAct.mp4',
  },
  {
    id: 2,
    author: 'Andy William',
    video_title: 'Basic: how to ride your skateboard comfortly',
    duration: '7 min',
    views: '32K',
    thumbnail: videoThumbnail,
    type: 'free',
    videoLink: 'https://www.taxmann.com/emailer/images/CompaniesAct.mp4',
  },
  {
    id: 3,
    author: 'Andy William',
    video_title: 'Basic: how to ride your skateboard comfortly',
    duration: '7 min',
    views: '32K',
    thumbnail: videoThumbnail,
    type: 'free',
    videoLink: 'http://api.evorium.xyz/courses/5138821397.mp4',
  },
];
